name: env_tools
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::samtools
  - bioconda::bcftools
  - bioconda::tabix
  - bioconda::shapeit5
  - bioconda::htslib