name: env_tools
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - samtools
  - bcftools
  - tabix
  - shapeit5
  - htslib
  - plink
  - r-base>=4
  - r-essentials
  - r-optparse
  - bioconda::vcflib=1.0
  - bioconda::glimpse-bio=2.0.0
