name: env_tools
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::samtools
  - bioconda::bcftools
  - bioconda::tabix
  - bioconda::shapeit5
  - bioconda::htslib
  - bioconda::plink
  - conda-forge::r-base>=4
  - conda-forge::r-essentials
  - conda-forge::r-optparse